version: '3.7'

services:
  vue-js-pwa-sample:
    container_name: vue-js-pwa-sample-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
